### PR TITLE
docs: add mkdocs workflow

### LINKED ISSUE #5: Add a workflow to publish the docs with github actions
Material for MkDocs generated documentation can be created with a GitHub workflow. Adding this will ensure the documentation gets updated in-sync with the codebase.

Here's an example: https://sugatoray.github.io/TrustLLM/index.html

Go to settings of this repository, then choose `Pages` and then select `gh-pages` as the branch and `/root` as the location. Mkdocs will produce the website artifacts inside the `gh-pages` branch and not populalet the `main` branch with the artifacts in the `site` folder.

### PR DESCRIPTION
**Pull request by sugatoray**
Closes #5.

This will ensure that the workflow is added.

And will remove the `site` folder and the workflow will autogenerate the contents of the site folder inside the `gh-pages` branch (if not present already, will get created once the PR is added). For more details, please refer to the issue #5.

Here's the example: https://sugatoray.github.io/TrustLLM/index.html

### CODE REVIEW

**Comment by sugatoray** [comment]
@HowieHwong Are you using the contents of the `site` folder to produce this website?
- https://trustllmbenchmark.github.io/TrustLLM-Website/index.html

:fire: **If yes, then please wait until I make a change.** 

If not, you should be fine as long as you are using a `squash` merge to keep the git history clean.

**Comment by HowieHwong** [comment]
> @HowieHwong Are you using the contents of the `site` folder to produce this website?
> 
> * https://trustllmbenchmark.github.io/TrustLLM-Website/index.html
> 
> **If yes, then please wait until I make a change.**
> 
> If not, you should be fine as long as you are using a `squash` merge to keep the git history clean.

Hi, thanks a lot for your contributions! We do not use `site` for the website `'https://trustllmbenchmark.github.io/TrustLLM-Website/index.html'`. The `site` is generated by `mkdocs gh-deploy`.

**Comment by sugatoray** [comment]
Ok. Then this PR should not cause any problem. Please feel free to `SQUASH merge` it if everything looks okay to you.

cc: @HowieHwong

**Comment by sugatoray** [comment]
@HowieHwong: I see that the workflow failed. Please have your Pages setting as this one.
The URL will be auto-generated for you. What is important here is the `Branch` settings as `gh-pages`.

image

**Comment by HowieHwong** [comment]
image

However, it seems originally I'm using `gh-pages` branch. The error may be caused by other reasons?

**Comment by sugatoray** [comment]
Interesting!... Let me examine the error once again.

However, when I pull the `main` branch updates from your main branch to mine (sync my fork), it triggers a successful workflow build.
image

**Comment by sugatoray** [comment]
@HowieHwong: The error says that there was a permission issue for your repository.

> ```sh
> remote: Permission to HowieHwong/TrustLLM.git denied to github-actions[bot].
> ```

👉 This could be the solution. https://github.com/ad-m/github-push-action/issues/96#issuecomment-1647904286

```sh
Switching to branch: 
Your branch is up to date with 'origin/main'.
Current Git Branch: 
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /home/runner/work/TrustLLM/TrustLLM/site
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - guide.md
INFO    -  Documentation built in 0.45 seconds
WARNING -  Version check skipped: No version specified in previous deployment.
INFO    -  Copying '/home/runner/work/TrustLLM/TrustLLM/site' to 'gh-pages' branch and pushing to GitHub.
remote: Permission to HowieHwong/TrustLLM.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/HowieHwong/TrustLLM/': The requested URL returned error: 403
```

**Comment by HowieHwong** [comment]
> @HowieHwong: The error says that there was a permission issue for your repository.
> 
> > ```shell
> > remote: Permission to HowieHwong/TrustLLM.git denied to github-actions[bot].
> > ```
> 
> 👉 This could be the solution. [ad-m/github-push-action#96 (comment)](https://github.com/ad-m/github-push-action/issues/96#issuecomment-1647904286)
> 
> ```shell
> Switching to branch: 
> Your branch is up to date with 'origin/main'.
> Current Git Branch: 
> INFO    -  Cleaning site directory
> INFO    -  Building documentation to directory: /home/runner/work/TrustLLM/TrustLLM/site
> INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
>   - guide.md
> INFO    -  Documentation built in 0.45 seconds
> WARNING -  Version check skipped: No version specified in previous deployment.
> INFO    -  Copying '/home/runner/work/TrustLLM/TrustLLM/site' to 'gh-pages' branch and pushing to GitHub.
> remote: Permission to HowieHwong/TrustLLM.git denied to github-actions[bot].
> fatal: unable to access 'https://github.com/HowieHwong/TrustLLM/': The requested URL returned error: 403
> ```

I have changed the permission. Now it works! Thank you for your feedback 👍

**Pull request merged**
